/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// Use environment variables in production, fallback to local dev values
export const projectId = (typeof import.meta !== 'undefined' && import.meta.env?.VITE_SUPABASE_PROJECT_ID) || "mrlukocaomzxinurpwnq"
export const publicAnonKey = (typeof import.meta !== 'undefined' && import.meta.env?.VITE_SUPABASE_ANON_KEY) || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ybHVrb2Nhb216eGludXJwd25xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM3MTAwNDgsImV4cCI6MjA3OTI4NjA0OH0.ejVaLQhEwoONGQhB_qimkTGJV12D3L8xVq3qhR4Iqec"
